<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Multiclass-Classification-with-Iris-Data" data-toc-modified-id="Multiclass-Classification-with-Iris-Data-1">Multiclass Classification with Iris Data</a></span></li><li><span><a href="#Evaluation-Metrics" data-toc-modified-id="Evaluation-Metrics-2">Evaluation Metrics</a></span></li></ul></div>

<center><h2>Multiclass Classification with Iris Data</h2></center>

<center><img src="../images/iris_petal_sepal.png" width="35%"/></center>

In [9]:
reset -fs

In [10]:
# Load data for modeling
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)

Let's check out the documentation for [LogisticRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)

In [11]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(multi_class='multinomial',
                         solver='newton-cg')
clf.fit(X, y)

LogisticRegression(multi_class='multinomial', solver='newton-cg')

In [29]:
# Randomly pick an observation 
import numpy as np

i = np.random.choice(X.shape[0])
sample = X[i].reshape(1, -1)
print(f"Data observation at index {i} has the following feature values:") 
for name, value in zip(sample[0], load_iris().feature_names):
    print(f"- {value:<17}: {name}")

Data observation at index 77 has the following feature values:
- sepal length (cm): 6.7
- sepal width (cm) : 3.0
- petal length (cm): 5.0
- petal width (cm) : 1.7


In [13]:
# TODO: Find predicted probabilities of each class for a sample data point.
# These are the raw values for softmax. 
# The largest probablity is the predict of the current model for the current data point.






In [14]:
# Solutions
clf.predict_proba(sample)

for k, v in enumerate(clf.predict_proba(sample)[0]):
    print(f"For class {k}, the probability is {v:.5f}")

For class 0, the probability is 0.98647
For class 1, the probability is 0.01353
For class 2, the probability is 0.00000


Evaluation Metrics
------

In [15]:
# TODO:
# 1. Import `confusion_matrix` and `classification_report` functions 
# 2. Create confusion matrix and classification_report for all data points.
# 3. Interpert
#    - Where does the model do well?
#    - What kind of mistakes does the model make?








array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [18]:
# Solutions

y_pred = clf.predict(X)
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y, y_pred)
print(cm)

from sklearn.metrics import classification_report
print(classification_report(y, y_pred, target_names=load_iris().target_names))

# Notes:
# Overall the model does very well 
# It does perfectly for class setosa
# 

[[50  0  0]
 [ 0 47  3]
 [ 0  1 49]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        50
  versicolor       0.98      0.94      0.96        50
   virginica       0.94      0.98      0.96        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97       150



<br>
<br> 
<br>

----